version: '2.2'
services:
  vh-dash:
    image: "${IMAGE_NAME}"
    cpus: '0.1'
    mem_limit: 50M
    ports:
      - 8080:80
    volumes:
      - /opt/$CI_PROJECT_PATH/public/config/:/usr/share/nginx/html/config/
networks:
    default:
        external:
            name: vh