const languages = [
  { ISO: "ab", label: "Abkhazian", code: "Abkhazian" },
  { ISO: "aa", label: "Afar", code: "Afar" },
  { ISO: "af", label: "Afrikaans", code: "Afrikaans" },
  { ISO: "ak", label: "Akan", code: "Akan" },
  { ISO: "sq", label: "Albanian", code: "Albanian" },
  { ISO: "am", label: "Amharic", code: "Amharic" },
  { ISO: "ar", label: "Arabic", code: "Arabic" },
  { ISO: "an", label: "Aragonese", code: "Aragonese" },
  { ISO: "hy", label: "Armenian", code: "Armenian" },
  { ISO: "as", label: "Assamese", code: "Assamese" },
  { ISO: "av", label: "Avaric", code: "Avaric" },
  { ISO: "ae", label: "Avestan", code: "Avestan" },
  { ISO: "ay", label: "Aymara", code: "Aymara" },
  { ISO: "az", label: "Azerbaijani", code: "Azerbaijani" },
  { ISO: "bm", label: "Bambara", code: "Bambara" },
  { ISO: "ba", label: "Bashkir", code: "Bashkir" },
  { ISO: "eu", label: "Basque", code: "Basque" },
  { ISO: "be", label: "Belarusian", code: "Belarusian" },
  { ISO: "bn", label: "Bengali", code: "Bengali" },
  { ISO: "bh", label: "Bihari languages", code: "Bihari languages" },
  { ISO: "bi", label: "Bislama", code: "Bislama" },
  { ISO: "bs", label: "Bosnian", code: "Bosnian" },
  { ISO: "br", label: "Breton", code: "Breton" },
  { ISO: "bg", label: "Bulgarian", code: "Bulgarian" },
  { ISO: "my", label: "Burmese", code: "Burmese" },
  { ISO: "ca", label: "Catalan, Valencian", code: "Catalan, Valencian" },
  { ISO: "km", label: "Central Khmer", code: "Central Khmer" },
  { ISO: "ch", label: "Chamorro", code: "Chamorro" },
  { ISO: "ce", label: "Chechen", code: "Chechen" },
  {
    ISO: "ny",
    label: "Chichewa, Chewa, Nyanja",
    code: "Chichewa, Chewa, Nyanja",
  },
  { ISO: "zh", label: "Chinese", code: "Chinese" },
  {
    ISO: "cu",
    label: "Church Slavonic, Old Bulgarian, Old Church Slavonic",
    code: "Church Slavonic, Old Bulgarian, Old Church Slavonic",
  },
  { ISO: "cv", label: "Chuvash", code: "Chuvash" },
  { ISO: "kw", label: "Cornish", code: "Cornish" },
  { ISO: "co", label: "Corsican", code: "Corsican" },
  { ISO: "cr", label: "Cree", code: "Cree" },
  { ISO: "hr", label: "Croatian", code: "Croatian" },
  { ISO: "cs", label: "Czech", code: "Czech" },
  { ISO: "da", label: "Danish", code: "Danish" },
  {
    ISO: "dv",
    label: "Divehi, Dhivehi, Maldivian",
    code: "Divehi, Dhivehi, Maldivian",
  },
  { ISO: "nl", label: "Dutch, Flemish", code: "Dutch, Flemish" },
  { ISO: "dz", label: "Dzongkha", code: "Dzongkha" },
  { ISO: "en", label: "English", code: "English" },
  { ISO: "eo", label: "Esperanto", code: "Esperanto" },
  { ISO: "et", label: "Estonian", code: "Estonian" },
  { ISO: "ee", label: "Ewe", code: "Ewe" },
  { ISO: "fo", label: "Faroese", code: "Faroese" },
  { ISO: "fj", label: "Fijian", code: "Fijian" },
  { ISO: "fi", label: "Finnish", code: "Finnish" },
  { ISO: "fr", label: "French", code: "French" },
  { ISO: "ff", label: "Fulah", code: "Fulah" },
  {
    ISO: "gd",
    label: "Gaelic, Scottish Gaelic",
    code: "Gaelic, Scottish Gaelic",
  },
  { ISO: "gl", label: "Galician", code: "Galician" },
  { ISO: "lg", label: "Ganda", code: "Ganda" },
  { ISO: "ka", label: "Georgian", code: "Georgian" },
  { ISO: "de", label: "German", code: "German" },
  { ISO: "ki", label: "Gikuyu, Kikuyu", code: "Gikuyu, Kikuyu" },
  { ISO: "el", label: "Greek (Modern)", code: "Greek (Modern)" },
  {
    ISO: "kl",
    label: "Greenlandic, Kalaallisut",
    code: "Greenlandic, Kalaallisut",
  },
  { ISO: "gn", label: "Guarani", code: "Guarani" },
  { ISO: "gu", label: "Gujarati", code: "Gujarati" },
  {
    ISO: "ht",
    label: "Haitian, Haitian Creole",
    code: "Haitian, Haitian Creole",
  },
  { ISO: "ha", label: "Hausa", code: "Hausa" },
  { ISO: "he", label: "Hebrew", code: "Hebrew" },
  { ISO: "hz", label: "Herero", code: "Herero" },
  { ISO: "hi", label: "Hindi", code: "Hindi" },
  { ISO: "ho", label: "Hiri Motu", code: "Hiri Motu" },
  { ISO: "hu", label: "Hungarian", code: "Hungarian" },
  { ISO: "is", label: "Icelandic", code: "Icelandic" },
  { ISO: "io", label: "Ido", code: "Ido" },
  { ISO: "ig", label: "Igbo", code: "Igbo" },
  { ISO: "id", label: "Indonesian", code: "Indonesian" },
  {
    ISO: "ia",
    label: "Interlingua (International Auxiliary Language Association)",
    code: "Interlingua (International Auxiliary Language Association)",
  },
  { ISO: "ie", label: "Interlingue", code: "Interlingue" },
  { ISO: "iu", label: "Inuktitut", code: "Inuktitut" },
  { ISO: "ik", label: "Inupiaq", code: "Inupiaq" },
  { ISO: "ga", label: "Irish", code: "Irish" },
  { ISO: "it", label: "Italian", code: "Italian" },
  { ISO: "ja", label: "Japanese", code: "Japanese" },
  { ISO: "jv", label: "Javanese", code: "Javanese" },
  { ISO: "kn", label: "Kannada", code: "Kannada" },
  { ISO: "kr", label: "Kanuri", code: "Kanuri" },
  { ISO: "ks", label: "Kashmiri", code: "Kashmiri" },
  { ISO: "kk", label: "Kazakh", code: "Kazakh" },
  { ISO: "rw", label: "Kinyarwanda", code: "Kinyarwanda" },
  { ISO: "kv", label: "Komi", code: "Komi" },
  { ISO: "kg", label: "Kongo", code: "Kongo" },
  { ISO: "ko", label: "Korean", code: "Korean" },
  { ISO: "kj", label: "Kwanyama, Kuanyama", code: "Kwanyama, Kuanyama" },
  { ISO: "ku", label: "Kurdish", code: "Kurdish" },
  { ISO: "ky", label: "Kyrgyz", code: "Kyrgyz" },
  { ISO: "lo", label: "Lao", code: "Lao" },
  { ISO: "la", label: "Latin", code: "Latin" },
  { ISO: "lv", label: "Latvian", code: "Latvian" },
  {
    ISO: "lb",
    label: "Letzeburgesch, Luxembourgish",
    code: "Letzeburgesch, Luxembourgish",
  },
  {
    ISO: "li",
    label: "Limburgish, Limburgan, Limburger",
    code: "Limburgish, Limburgan, Limburger",
  },
  { ISO: "ln", label: "Lingala", code: "Lingala" },
  { ISO: "lt", label: "Lithuanian", code: "Lithuanian" },
  { ISO: "lu", label: "Luba-Katanga", code: "Luba-Katanga" },
  { ISO: "mk", label: "Macedonian", code: "Macedonian" },
  { ISO: "mg", label: "Malagasy", code: "Malagasy" },
  { ISO: "ms", label: "Malay", code: "Malay" },
  { ISO: "ml", label: "Malayalam", code: "Malayalam" },
  { ISO: "mt", label: "Maltese", code: "Maltese" },
  { ISO: "gv", label: "Manx", code: "Manx" },
  { ISO: "mi", label: "Maori", code: "Maori" },
  { ISO: "mr", label: "Marathi", code: "Marathi" },
  { ISO: "mh", label: "Marshallese", code: "Marshallese" },
  {
    ISO: "ro",
    label: "Moldovan, Moldavian, Romanian",
    code: "Moldovan, Moldavian, Romanian",
  },
  { ISO: "mn", label: "Mongolian", code: "Mongolian" },
  { ISO: "na", label: "Nauru", code: "Nauru" },
  { ISO: "nv", label: "Navajo, Navaho", code: "Navajo, Navaho" },
  { ISO: "nd", label: "Northern Ndebele", code: "Northern Ndebele" },
  { ISO: "ng", label: "Ndonga", code: "Ndonga" },
  { ISO: "ne", label: "Nepali", code: "Nepali" },
  { ISO: "se", label: "Northern Sami", code: "Northern Sami" },
  { ISO: "no", label: "Norwegian", code: "Norwegian" },
  { ISO: "nb", label: "Norwegian Bokmål", code: "Norwegian Bokmål" },
  { ISO: "nn", label: "Norwegian Nynorsk", code: "Norwegian Nynorsk" },
  { ISO: "ii", label: "Nuosu, Sichuan Yi", code: "Nuosu, Sichuan Yi" },
  { ISO: "oc", label: "Occitan (post 1500)", code: "Occitan (post 1500)" },
  { ISO: "oj", label: "Ojibwa", code: "Ojibwa" },
  { ISO: "or", label: "Oriya", code: "Oriya" },
  { ISO: "om", label: "Oromo", code: "Oromo" },
  { ISO: "os", label: "Ossetian, Ossetic", code: "Ossetian, Ossetic" },
  { ISO: "pi", label: "Pali", code: "Pali" },
  { ISO: "pa", label: "Panjabi, Punjabi", code: "Panjabi, Punjabi" },
  { ISO: "ps", label: "Pashto, Pushto", code: "Pashto, Pushto" },
  { ISO: "fa", label: "Persian", code: "Persian" },
  { ISO: "pl", label: "Polish", code: "Polish" },
  { ISO: "pt", label: "Portuguese", code: "Portuguese" },
  { ISO: "qu", label: "Quechua", code: "Quechua" },
  { ISO: "rm", label: "Romansh", code: "Romansh" },
  { ISO: "rn", label: "Rundi", code: "Rundi" },
  { ISO: "ru", label: "Russian", code: "Russian" },
  { ISO: "sm", label: "Samoan", code: "Samoan" },
  { ISO: "sg", label: "Sango", code: "Sango" },
  { ISO: "sa", label: "Sanskrit", code: "Sanskrit" },
  { ISO: "sc", label: "Sardinian", code: "Sardinian" },
  { ISO: "sr", label: "Serbian", code: "Serbian" },
  { ISO: "sn", label: "Shona", code: "Shona" },
  { ISO: "sd", label: "Sindhi", code: "Sindhi" },
  { ISO: "si", label: "Sinhala, Sinhalese", code: "Sinhala, Sinhalese" },
  { ISO: "sk", label: "Slovak", code: "Slovak" },
  { ISO: "sl", label: "Slovenian", code: "Slovenian" },
  { ISO: "so", label: "Somali", code: "Somali" },
  { ISO: "st", label: "Sotho, Southern", code: "Sotho, Southern" },
  { ISO: "nr", label: "South Ndebele", code: "South Ndebele" },
  { ISO: "es", label: "Spanish, Castilian", code: "Spanish, Castilian" },
  { ISO: "su", label: "Sundanese", code: "Sundanese" },
  { ISO: "sw", label: "Swahili", code: "Swahili" },
  { ISO: "ss", label: "Swati", code: "Swati" },
  { ISO: "sv", label: "Swedish", code: "Swedish" },
  { ISO: "tl", label: "Tagalog", code: "Tagalog" },
  { ISO: "ty", label: "Tahitian", code: "Tahitian" },
  { ISO: "tg", label: "Tajik", code: "Tajik" },
  { ISO: "ta", label: "Tamil", code: "Tamil" },
  { ISO: "tt", label: "Tatar", code: "Tatar" },
  { ISO: "te", label: "Telugu", code: "Telugu" },
  { ISO: "th", label: "Thai", code: "Thai" },
  { ISO: "bo", label: "Tibetan", code: "Tibetan" },
  { ISO: "ti", label: "Tigrinya", code: "Tigrinya" },
  { ISO: "to", label: "Tonga (Tonga Islands)", code: "Tonga (Tonga Islands)" },
  { ISO: "ts", label: "Tsonga", code: "Tsonga" },
  { ISO: "tn", label: "Tswana", code: "Tswana" },
  { ISO: "tr", label: "Turkish", code: "Turkish" },
  { ISO: "tk", label: "Turkmen", code: "Turkmen" },
  { ISO: "tw", label: "Twi", code: "Twi" },
  { ISO: "ug", label: "Uighur, Uyghur", code: "Uighur, Uyghur" },
  { ISO: "uk", label: "Ukrainian", code: "Ukrainian" },
  { ISO: "ur", label: "Urdu", code: "Urdu" },
  { ISO: "uz", label: "Uzbek", code: "Uzbek" },
  { ISO: "ve", label: "Venda", code: "Venda" },
  { ISO: "vi", label: "Vietlabelse", code: "Vietlabelse" },
  { ISO: "vo", label: "Volap_k", code: "Volap_k" },
  { ISO: "wa", label: "Walloon", code: "Walloon" },
  { ISO: "cy", label: "Welsh", code: "Welsh" },
  { ISO: "fy", label: "Western Frisian", code: "Western Frisian" },
  { ISO: "wo", label: "Wolof", code: "Wolof" },
  { ISO: "xh", label: "Xhosa", code: "Xhosa" },
  { ISO: "yi", label: "Yiddish", code: "Yiddish" },
  { ISO: "yo", label: "Yoruba", code: "Yoruba" },
  { ISO: "za", label: "Zhuang, Chuang", code: "Zhuang, Chuang" },
  { ISO: "zu", label: "Zulu", code: "Zulu" },
];

export default languages;
