export const HEARTBEAT_INTERVAL = 5000;
export const SET_THEME = "SET_THEME";
export const SET_SETTINGS = "SET_SETTINGS";
export const CHANGE_BITRATE = "CHANGE_BITRATE";
export const CHANGE_VOLUME = "CHANGE_VOLUME";
export const REQUEST_HEARTBEAT = "REQUEST_HEARTBEAT";
export const RECEIVE_HEARTBEAT = "RECEIVE_HEARTBEAT";
export const REQUEST_STREAMS = "REQUEST_STREAMS";
export const RECEIVE_STREAMS = "RECEIVE_STREAMS";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

// User Profile types
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const FETCH_PROFILE_FAILED = "FETCH_PROFILE_FAILED";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";
export const TOGGLE_PROFILE_WINDOW = "TOGGLE_PROFILE_WINDOW";

//User Reducers
export const SET_LOGGEDIN_USER = "SET_LOGGEDIN_USER";
export const SET_FIRST_NAME = "SET_FIRST_NAME";
export const SET_LAST_NAME = "SET_LAST_NAME";
export const SET_KEYCLOAK_DATA = "SET_KEYCLOAK_DATA";

//Customers Reducers
export const SEARCH_CUSTOMERS_SUCCESS = "SEARCH_CUSTOMERS_SUCCESS";
export const SEARCH_CUSTOMERS_FAILED = "SEARCH_CUSTOMERS_FAILED";
export const SET_CUSTOMERS_LOADING = "SET_CUSTOMERS_LOADING";
export const FETCH_ACTIVITY_SUCCESS = "FETCH_ACTIVITY_SUCCESS";
export const FETCH_ACTIVITY_FAILED = "FETCH_ACTIVITY_FAILED";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED";
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_FAILED = "GET_PAYMENTS_FAILED";
export const FETCH_SPECIALS_SUCCESS = "FETCH_SPECIALS_SUCCESS";
export const FETCH_SPECIALS_FAILED = "FETCH_SPECIALS_FAILED";

//Help Haver
export const SET_HELP_HAVER_LOADING = "SET_HELP_HAVER_LOADING";
export const GET_MEMBERSHIP_REQUESTS_SUCCESS =
  "GET_MEMBERSHIP_REQUESTS_SUCCESS";
export const GET_MEMBERSHIP_REQUESTS_FAILED = "GET_MEMBERSHIP_REQUESTS_FAILED";
export const GET_REQUESTOR_DETAILS_SUCCESS = "GET_REQUESTOR_DETAILS_SUCCESS";
export const GET_REQUESTOR_DETAILS_FAILED = "GET_REQUESTOR_DETAILS_FAILED";
export const SAVE_MERGE_DETAILS = "SAVE_MERGE_DETAILS";
