# Expires map
map $sent_http_content_type $expires {
    default                    off;
    text/html                  epoch;
    text/css                   max;
    application/json           max;
    application/javascript     max;
    ~image/                    max;
}

server {
  listen 80;
  location / {
      expires $expires;
      root /usr/share/nginx/html;
      index index.html index.htm;
      try_files $uri $uri/ /index.html =404;
  }
  location ~ /payments/(.*) {
      expires $expires;
      root /usr/share/nginx/html;
      index index.html index.htm;
      try_files $uri $uri/ /index.html =404;
  }
  location ~ /config/(.*) {
      root /usr/share/nginx/html;
      expires -1;
      index index.html index.htm;
      try_files $uri $uri/ /index.html =404;
  }
  location ~ /payments/config/(.*) {
      root /usr/share/nginx/html/config;
      expires -1;
      index index.html index.htm;
      try_files $uri $uri/ /index.html =404;
  }
  gzip  on;
  gzip_http_version 1.0; 
  gzip_comp_level 5; # 1-9 
  gzip_min_length 256;
  gzip_proxied any; 
  gzip_vary on;

}
